<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var string $label Default to "Log in".
 * @var string $loginElement May be "link" (default) or "button".
 *
 * Display an elemnt to call the login page or dialog.
 * Can be used in any theme.
 *
 * @todo Add option "auto": when there is a dialog for login, use button, else display a link.
 * @todo Check if there is a login page to get the right url.
 */

if ($this->identity()) return;

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$site = $plugins->get('currentSite')();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$basePath = $plugins->get('basePath');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$label ??= $translate('Log in');
$loginElement ??= 'link';

// Do not redirect to admin login page, so force /s/xxx/ even when CleanUrl is enabled.
$urlLogin = $site ? $basePath() . '/s/' . $site->slug() . '/guest/login' : $url('forgot-password');
?>

<div class="login-container">

    <?php if ($loginElement === 'button'): ?>

        <button type="button" class="button user-login login-button" title="<?= $escapeAttr($label) ?>" data-url="<?= $escapeAttr($urlLogin) ?>">
            <span class="icon-login"><?= $escape($label) ?></span>
        </button>

    <?php else: ?>

        <a href="<?= $escapeAttr($urlLogin) ?>" class="user-login login-link">
            <span class="icon-login"><?= $escape($label) ?></span>
        </a>

    <?php endif; ?>

</div>
