<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 */

$translate = $this->plugin('translate');
?>

<h1><?= $translate('Authentication error') ?></h1>

<p>
    <?= $translate('An error occurred during the authentication via a third party authenticator.') ?>
</p>
<p>
    <?= $translate('Contact your administrator for more information.') ?>
</p>
