<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Form\LoginForm|null $form
 * @var \Omeka\Form\UserForm|null $formRegister
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$trigger = $plugins->get('trigger');
$setting = $plugins->get('setting');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$pageTitle = $plugins->get('pageTitle');
$siteSetting = $plugins->get('siteSetting');
$htmlElement = $plugins->get('htmlElement');

$htmlElement('body')->appendAttribute('class', 'guest login');

if ($form) $form->prepare();
if ($formRegister) $formRegister->prepare();
?>

<?= $pageTitle($siteSetting('guest_login_text') ?: ($setting('guest_login_text') ?: $translate('Login'))) ?>

<div class="guest-anonymous guest-login">

    <?= $this->messages() ?>

    <?php if ($form): ?>
    <?= $this->form($form) ?>
    <p class="forgot-password">
        <?= $hyperlink($translate('Forgot password?'), $url('site/guest/anonymous', ['action' => 'forgot-password'], true)) ?>
    </p>
    <?php endif; ?>

    <?php $trigger('view.login.after'); ?>

</div>

<?php if ($formRegister): ?>
<div class="guest-anonymous guest-register">

    <?= $this->messages() ?>

    <div>
        <?= $siteSetting('guest_capabilities') ?: $setting('guest_capabilities') ?>
    </div>

    <?= $this->form()->openTag($formRegister) ?>
        <?= $this->formCollection($formRegister, false) ?>
        <?php $trigger('view.add.form.after'); ?>
        <div id="page-actions">
            <button type="submit"><?= $translate('Register') ?></button>
        </div>
    <?= $this->form()->closeTag() ?>

    <?php $trigger('view.add.after'); ?>

</div>
<?php endif; ?>
