<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$basePath = $plugins->get('basePath');

$site = $plugins->get('currentSite')();
?>

<ul>
    <li>
        <?php $href = $url('site/guest/guest', ['action' => 'update-account'], [], true); ?>
        <?= $hyperlink($translate('Update account info and password'), $href) ?>
    </li>
    <li>
        <?php $href = $url('site/guest/guest', ['action' => 'update-email'], [], true); ?>
        <?= $hyperlink($translate('Update email'), $href) ?>
    </li>
    <li>
        <?php $href = $basePath() . '/s/' . $site->slug() . '/guest/logout'; ?>
        <?= $hyperlink($translate('Logout'), $href) ?>
    </li>
</ul>
