<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Form\ForgotPasswordForm $form
 */

$plugins = $this->getHelperPluginManager();
$trigger = $plugins->get('trigger');
$translate = $plugins->get('translate');
$siteSetting = $plugins->get('siteSetting');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$htmlBefore = $siteSetting('guest_forgot_password_html_before');
$htmlAfter = $siteSetting('guest_forgot_password_html_after');

$form->prepare();
?>

<dialog id="forgot-password" class="popup popup-dialog dialog-forgot-password" aria-labelledby="dialog-forgot-password-heading">
    <div class="dialog-background">
        <div class="dialog-panel">
            <div class="dialog-header">
                <button type="button" class="dialog-header-close-button">
                    <span class="dialog-close" aria-hidden="true">🗙</span>
                    <span class="dialog-close-label"><?= $this->translate('Close') ?></span>
                </button>
                <div class="dialog-messages" role="status" aria-live="polite">
                </div>
            </div>
            <div class="dialog-contents">
                <h2 id="dialog-forgot-password-heading" class="dialog-heading"><?= $translate('Forgot password?') ?></h2>
                <?php if ($htmlBefore): ?>
                <div class="contents-before">
                    <?= $htmlBefore ?>
                </div>
                <?php endif; ?>
                <?= $this->form()->openTag($form) ?>
                    <?= $this->formCollection($form, false) ?>
                    <?php $trigger('view.add.form.after'); ?>
                    <button type="submit"><?= $translate('Submit') ?></button>
                <?= $this->form()->closeTag() ?>
                <?php if ($htmlAfter): ?>
                <div class="contents-after">
                    <?= $htmlAfter ?>
                </div>
                <?php endif; ?>
            </div>
            <div class="dialog-footer">
                <?php $trigger('view.add.after'); ?>
            </div>
        </div>
    </div>
</dialog>
