<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Form\ForgotPasswordForm $form
 */

$plugins = $this->getHelperPluginManager();
$trigger = $plugins->get('trigger');
$translate = $plugins->get('translate');
$siteSetting = $plugins->get('siteSetting');

$htmlBefore = $siteSetting('guest_forgot_password_html_before');
$htmlAfter = $siteSetting('guest_forgot_password_html_after');

$form->prepare();
?>

<dialog id="forgot-password" class="popup popup-dialog dialog-forgot-password">
    <div class="dialog-background">
        <div class="dialog-panel">
            <div class="dialog-header">
                <button type="button" class="dialog-header-close-button" title="<?= $translate('Close') ?>" autofocus="autofocus">
                    <span class="dialog-close">🗙</span>
                </button>
                <div class="dialog-messages">
                </div>
            </div>
            <div class="dialog-contents">
                <?php if ($htmlBefore): ?>
                <div class="contents-before">
                    <?= $htmlBefore ?>
                </div>
                <?php endif; ?>
                <?= $this->form()->openTag($form) ?>
                    <?= $this->formCollection($form, false) ?>
                    <?php $trigger('view.add.form.after'); ?>
                    <button type="submit"><?= $translate('Submit') ?></button>
                <?= $this->form()->closeTag() ?>
                <?php if ($htmlAfter): ?>
                <div class="contents-after">
                    <?= $htmlAfter ?>
                </div>
                <?php endif; ?>
            </div>
            <div class="dialog-footer">
                <?php $trigger('view.add.after'); ?>
            </div>
        </div>
    </div>
</dialog>
