<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Form\LoginForm|\UserNames\Form\LoginForm $form
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$siteSetting = $plugins->get('siteSetting');

$htmlBefore = $siteSetting('guest_login_html_before');
$htmlAfter = $siteSetting('guest_login_html_after');
?>

<dialog id="login" class="popup popup-dialog dialog-login">
    <div class="dialog-background">
        <div class="dialog-panel">
            <div class="dialog-header">
                <button type="button" class="dialog-header-close-button" title="<?= $translate('Close') ?>" autofocus="autofocus">
                    <span class="dialog-close">🗙</span>
                </button>
                <div class="dialog-messages">
                </div>
            </div>
            <div class="dialog-contents">
                <?php if ($htmlBefore): ?>
                <div class="contents-before">
                    <?= $htmlBefore ?>
                </div>
                <?php endif; ?>
                <?php if ($form): ?>
                <?= $this->form($form) ?>
                <p class="dialog-link link-forgot-password">
                    <?= $hyperlink($translate('Forgot password?'), $url('forgot-password'), ['class' => 'button-forgot-password']) ?>
                </p>
                <?php endif; ?>
                <?php if ($htmlAfter): ?>
                <div class="contents-after">
                    <?= $htmlAfter ?>
                </div>
                <?php endif; ?>
            </div>
            <div class="dialog-footer">
                <?php $this->trigger('view.login.after'); ?>
            </div>
        </div>
    </div>
</dialog>
